In [1]:
import tensorflow as tf
import numpy as np

In [3]:
tf.reset_default_graph()
#1. Experimenting with the  while loop
condition  = lambda i, _ : i< 10  # This is the conditoonal stateent that tells whether we should continue with the statement
body = lambda i, jk : (i+1, (jk[0]+jk[1],jk[0]-jk[1])) # this is the body part that actually tells the computation that has to be perormed in the while loop
ijk_0 = (0,(1,2)) #This is the initial set of values

(i_final,jk_final) = tf.while_loop(cond=condition,body=body,loop_vars=ijk_0)
with tf.Session() as sess:
    x = sess.run([i_final,jk_final])
print x

In [27]:
#2. Experimenting with tf.TensorArray
tf.reset_default_graph()
matrix = tf.get_variable("matrix",[3,3],initializer=tf.random_normal_initializer)

#Example Unpack + read

matrix_rows = tf.shape(matrix)[0]
ta = tf.TensorArray(tf.float32,size=matrix_rows)
ta = ta.unstack(matrix)
read_row = ta.read(1)


#Exampe Write + pack

ta = tf.TensorArray(tf.float32,size = matrix_rows)
ta = ta.write(1,np.array([1.0,2.0,3.0],dtype=np.float32))
read_row2 =  ta.read(1)


with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    mat,rr1,rr2 = sess.run([matrix,read_row,read_row2])
    new_matrix = ta.stack()
print mat
print rr1
print rr2

[[-0.39882767  0.91837859  0.17432871]
 [-0.73285705 -0.32578328  1.11920786]
 [ 0.03866017  0.09818452  0.08692422]]
[-0.73285705 -0.32578328  1.11920786]
[ 1.  2.  3.]
